/*
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: 1.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ActuatorDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T11:31:19.558Z")
public class ActuatorDTO {
  @SerializedName("condition")
  private Boolean condition = null;

  @SerializedName("delay1")
  private Long delay1 = null;

  @SerializedName("delay2")
  private Long delay2 = null;

  @SerializedName("send")
  private String send = null;

  @SerializedName("text")
  private String text = null;

  @SerializedName("uri")
  private String uri = null;

  public ActuatorDTO condition(Boolean condition) {
    this.condition = condition;
    return this;
  }

   /**
   * Get condition
   * @return condition
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCondition() {
    return condition;
  }

  public void setCondition(Boolean condition) {
    this.condition = condition;
  }

  public ActuatorDTO delay1(Long delay1) {
    this.delay1 = delay1;
    return this;
  }

   /**
   * Get delay1
   * @return delay1
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDelay1() {
    return delay1;
  }

  public void setDelay1(Long delay1) {
    this.delay1 = delay1;
  }

  public ActuatorDTO delay2(Long delay2) {
    this.delay2 = delay2;
    return this;
  }

   /**
   * Get delay2
   * @return delay2
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getDelay2() {
    return delay2;
  }

  public void setDelay2(Long delay2) {
    this.delay2 = delay2;
  }

  public ActuatorDTO send(String send) {
    this.send = send;
    return this;
  }

   /**
   * Get send
   * @return send
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSend() {
    return send;
  }

  public void setSend(String send) {
    this.send = send;
  }

  public ActuatorDTO text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public ActuatorDTO uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActuatorDTO actuatorDTO = (ActuatorDTO) o;
    return Objects.equals(this.condition, actuatorDTO.condition) &&
        Objects.equals(this.delay1, actuatorDTO.delay1) &&
        Objects.equals(this.delay2, actuatorDTO.delay2) &&
        Objects.equals(this.send, actuatorDTO.send) &&
        Objects.equals(this.text, actuatorDTO.text) &&
        Objects.equals(this.uri, actuatorDTO.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(condition, delay1, delay2, send, text, uri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActuatorDTO {\n");
    
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    delay1: ").append(toIndentedString(delay1)).append("\n");
    sb.append("    delay2: ").append(toIndentedString(delay2)).append("\n");
    sb.append("    send: ").append(toIndentedString(send)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

