/*
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: 1.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * LatestDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T11:31:19.558Z")
public class LatestDTO {
  @SerializedName("code")
  private Integer code = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("latest")
  private Double latest = null;

  @SerializedName("latestDay")
  private Double latestDay = null;

  @SerializedName("latestMin5")
  private Double latestMin5 = null;

  @SerializedName("latestMin60")
  private Double latestMin60 = null;

  @SerializedName("latestMonth")
  private Double latestMonth = null;

  @SerializedName("latestTime")
  private Long latestTime = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("uom")
  private String uom = null;

  @SerializedName("uri")
  private String uri = null;

  @SerializedName("url")
  private String url = null;

  public LatestDTO code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public LatestDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public LatestDTO latest(Double latest) {
    this.latest = latest;
    return this;
  }

   /**
   * Get latest
   * @return latest
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getLatest() {
    return latest;
  }

  public void setLatest(Double latest) {
    this.latest = latest;
  }

  public LatestDTO latestDay(Double latestDay) {
    this.latestDay = latestDay;
    return this;
  }

   /**
   * Get latestDay
   * @return latestDay
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getLatestDay() {
    return latestDay;
  }

  public void setLatestDay(Double latestDay) {
    this.latestDay = latestDay;
  }

  public LatestDTO latestMin5(Double latestMin5) {
    this.latestMin5 = latestMin5;
    return this;
  }

   /**
   * Get latestMin5
   * @return latestMin5
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getLatestMin5() {
    return latestMin5;
  }

  public void setLatestMin5(Double latestMin5) {
    this.latestMin5 = latestMin5;
  }

  public LatestDTO latestMin60(Double latestMin60) {
    this.latestMin60 = latestMin60;
    return this;
  }

   /**
   * Get latestMin60
   * @return latestMin60
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getLatestMin60() {
    return latestMin60;
  }

  public void setLatestMin60(Double latestMin60) {
    this.latestMin60 = latestMin60;
  }

  public LatestDTO latestMonth(Double latestMonth) {
    this.latestMonth = latestMonth;
    return this;
  }

   /**
   * Get latestMonth
   * @return latestMonth
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getLatestMonth() {
    return latestMonth;
  }

  public void setLatestMonth(Double latestMonth) {
    this.latestMonth = latestMonth;
  }

  public LatestDTO latestTime(Long latestTime) {
    this.latestTime = latestTime;
    return this;
  }

   /**
   * Get latestTime
   * @return latestTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getLatestTime() {
    return latestTime;
  }

  public void setLatestTime(Long latestTime) {
    this.latestTime = latestTime;
  }

  public LatestDTO status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public LatestDTO uom(String uom) {
    this.uom = uom;
    return this;
  }

   /**
   * Get uom
   * @return uom
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUom() {
    return uom;
  }

  public void setUom(String uom) {
    this.uom = uom;
  }

  public LatestDTO uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public LatestDTO url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LatestDTO latestDTO = (LatestDTO) o;
    return Objects.equals(this.code, latestDTO.code) &&
        Objects.equals(this.id, latestDTO.id) &&
        Objects.equals(this.latest, latestDTO.latest) &&
        Objects.equals(this.latestDay, latestDTO.latestDay) &&
        Objects.equals(this.latestMin5, latestDTO.latestMin5) &&
        Objects.equals(this.latestMin60, latestDTO.latestMin60) &&
        Objects.equals(this.latestMonth, latestDTO.latestMonth) &&
        Objects.equals(this.latestTime, latestDTO.latestTime) &&
        Objects.equals(this.status, latestDTO.status) &&
        Objects.equals(this.uom, latestDTO.uom) &&
        Objects.equals(this.uri, latestDTO.uri) &&
        Objects.equals(this.url, latestDTO.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, id, latest, latestDay, latestMin5, latestMin60, latestMonth, latestTime, status, uom, uri, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LatestDTO {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    latest: ").append(toIndentedString(latest)).append("\n");
    sb.append("    latestDay: ").append(toIndentedString(latestDay)).append("\n");
    sb.append("    latestMin5: ").append(toIndentedString(latestMin5)).append("\n");
    sb.append("    latestMin60: ").append(toIndentedString(latestMin60)).append("\n");
    sb.append("    latestMonth: ").append(toIndentedString(latestMonth)).append("\n");
    sb.append("    latestTime: ").append(toIndentedString(latestTime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    uom: ").append(toIndentedString(uom)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

