/*
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: 1.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * QueryResourceDataCriteriaDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T11:31:19.558Z")
public class QueryResourceDataCriteriaDTO {
  @SerializedName("resourceID")
  private Long resourceID = null;

  @SerializedName("resourceURI")
  private String resourceURI = null;

  public QueryResourceDataCriteriaDTO resourceID(Long resourceID) {
    this.resourceID = resourceID;
    return this;
  }

   /**
   * Get resourceID
   * @return resourceID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getResourceID() {
    return resourceID;
  }

  public void setResourceID(Long resourceID) {
    this.resourceID = resourceID;
  }

  public QueryResourceDataCriteriaDTO resourceURI(String resourceURI) {
    this.resourceURI = resourceURI;
    return this;
  }

   /**
   * Get resourceURI
   * @return resourceURI
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getResourceURI() {
    return resourceURI;
  }

  public void setResourceURI(String resourceURI) {
    this.resourceURI = resourceURI;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryResourceDataCriteriaDTO queryResourceDataCriteriaDTO = (QueryResourceDataCriteriaDTO) o;
    return Objects.equals(this.resourceID, queryResourceDataCriteriaDTO.resourceID) &&
        Objects.equals(this.resourceURI, queryResourceDataCriteriaDTO.resourceURI);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceID, resourceURI);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryResourceDataCriteriaDTO {\n");
    
    sb.append("    resourceID: ").append(toIndentedString(resourceID)).append("\n");
    sb.append("    resourceURI: ").append(toIndentedString(resourceURI)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

