/*
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: 1.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ResourceDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T11:31:19.558Z")
public class ResourceDTO {
  @SerializedName("command")
  private String command = null;

  @SerializedName("commandOff")
  private String commandOff = null;

  @SerializedName("commandOn")
  private String commandOn = null;

  @SerializedName("creationDate")
  private Long creationDate = null;

  @SerializedName("isa")
  private String isa = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("property")
  private String property = null;

  @SerializedName("resourceId")
  private Long resourceId = null;

  @SerializedName("tags")
  private List<String> tags = new ArrayList<String>();

  @SerializedName("uom")
  private String uom = null;

  @SerializedName("uri")
  private String uri = null;

  public ResourceDTO command(String command) {
    this.command = command;
    return this;
  }

   /**
   * Get command
   * @return command
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCommand() {
    return command;
  }

  public void setCommand(String command) {
    this.command = command;
  }

  public ResourceDTO commandOff(String commandOff) {
    this.commandOff = commandOff;
    return this;
  }

   /**
   * Get commandOff
   * @return commandOff
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCommandOff() {
    return commandOff;
  }

  public void setCommandOff(String commandOff) {
    this.commandOff = commandOff;
  }

  public ResourceDTO commandOn(String commandOn) {
    this.commandOn = commandOn;
    return this;
  }

   /**
   * Get commandOn
   * @return commandOn
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCommandOn() {
    return commandOn;
  }

  public void setCommandOn(String commandOn) {
    this.commandOn = commandOn;
  }

  public ResourceDTO creationDate(Long creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(Long creationDate) {
    this.creationDate = creationDate;
  }

  public ResourceDTO isa(String isa) {
    this.isa = isa;
    return this;
  }

   /**
   * Get isa
   * @return isa
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIsa() {
    return isa;
  }

  public void setIsa(String isa) {
    this.isa = isa;
  }

  public ResourceDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ResourceDTO property(String property) {
    this.property = property;
    return this;
  }

   /**
   * Get property
   * @return property
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProperty() {
    return property;
  }

  public void setProperty(String property) {
    this.property = property;
  }

  public ResourceDTO resourceId(Long resourceId) {
    this.resourceId = resourceId;
    return this;
  }

   /**
   * Get resourceId
   * @return resourceId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getResourceId() {
    return resourceId;
  }

  public void setResourceId(Long resourceId) {
    this.resourceId = resourceId;
  }

  public ResourceDTO tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public ResourceDTO addTagsItem(String tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public ResourceDTO uom(String uom) {
    this.uom = uom;
    return this;
  }

   /**
   * Get uom
   * @return uom
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUom() {
    return uom;
  }

  public void setUom(String uom) {
    this.uom = uom;
  }

  public ResourceDTO uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceDTO resourceDTO = (ResourceDTO) o;
    return Objects.equals(this.command, resourceDTO.command) &&
        Objects.equals(this.commandOff, resourceDTO.commandOff) &&
        Objects.equals(this.commandOn, resourceDTO.commandOn) &&
        Objects.equals(this.creationDate, resourceDTO.creationDate) &&
        Objects.equals(this.isa, resourceDTO.isa) &&
        Objects.equals(this.name, resourceDTO.name) &&
        Objects.equals(this.property, resourceDTO.property) &&
        Objects.equals(this.resourceId, resourceDTO.resourceId) &&
        Objects.equals(this.tags, resourceDTO.tags) &&
        Objects.equals(this.uom, resourceDTO.uom) &&
        Objects.equals(this.uri, resourceDTO.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(command, commandOff, commandOn, creationDate, isa, name, property, resourceId, tags, uom, uri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceDTO {\n");
    
    sb.append("    command: ").append(toIndentedString(command)).append("\n");
    sb.append("    commandOff: ").append(toIndentedString(commandOff)).append("\n");
    sb.append("    commandOn: ").append(toIndentedString(commandOn)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    isa: ").append(toIndentedString(isa)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    property: ").append(toIndentedString(property)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    uom: ").append(toIndentedString(uom)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

