/*
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: 1.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ShareDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T11:31:19.558Z")
public class ShareDTO {
  @SerializedName("code")
  private Integer code = null;

  @SerializedName("controlPermission")
  private Boolean controlPermission = null;

  @SerializedName("modifyPermission")
  private Boolean modifyPermission = null;

  @SerializedName("reusePermission")
  private Boolean reusePermission = null;

  @SerializedName("siteId")
  private Long siteId = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("viewPermission")
  private Boolean viewPermission = null;

  public ShareDTO code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public ShareDTO controlPermission(Boolean controlPermission) {
    this.controlPermission = controlPermission;
    return this;
  }

   /**
   * Get controlPermission
   * @return controlPermission
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getControlPermission() {
    return controlPermission;
  }

  public void setControlPermission(Boolean controlPermission) {
    this.controlPermission = controlPermission;
  }

  public ShareDTO modifyPermission(Boolean modifyPermission) {
    this.modifyPermission = modifyPermission;
    return this;
  }

   /**
   * Get modifyPermission
   * @return modifyPermission
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getModifyPermission() {
    return modifyPermission;
  }

  public void setModifyPermission(Boolean modifyPermission) {
    this.modifyPermission = modifyPermission;
  }

  public ShareDTO reusePermission(Boolean reusePermission) {
    this.reusePermission = reusePermission;
    return this;
  }

   /**
   * Get reusePermission
   * @return reusePermission
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getReusePermission() {
    return reusePermission;
  }

  public void setReusePermission(Boolean reusePermission) {
    this.reusePermission = reusePermission;
  }

  public ShareDTO siteId(Long siteId) {
    this.siteId = siteId;
    return this;
  }

   /**
   * Get siteId
   * @return siteId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSiteId() {
    return siteId;
  }

  public void setSiteId(Long siteId) {
    this.siteId = siteId;
  }

  public ShareDTO status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ShareDTO url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public ShareDTO username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public ShareDTO viewPermission(Boolean viewPermission) {
    this.viewPermission = viewPermission;
    return this;
  }

   /**
   * Get viewPermission
   * @return viewPermission
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getViewPermission() {
    return viewPermission;
  }

  public void setViewPermission(Boolean viewPermission) {
    this.viewPermission = viewPermission;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShareDTO shareDTO = (ShareDTO) o;
    return Objects.equals(this.code, shareDTO.code) &&
        Objects.equals(this.controlPermission, shareDTO.controlPermission) &&
        Objects.equals(this.modifyPermission, shareDTO.modifyPermission) &&
        Objects.equals(this.reusePermission, shareDTO.reusePermission) &&
        Objects.equals(this.siteId, shareDTO.siteId) &&
        Objects.equals(this.status, shareDTO.status) &&
        Objects.equals(this.url, shareDTO.url) &&
        Objects.equals(this.username, shareDTO.username) &&
        Objects.equals(this.viewPermission, shareDTO.viewPermission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, controlPermission, modifyPermission, reusePermission, siteId, status, url, username, viewPermission);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShareDTO {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    controlPermission: ").append(toIndentedString(controlPermission)).append("\n");
    sb.append("    modifyPermission: ").append(toIndentedString(modifyPermission)).append("\n");
    sb.append("    reusePermission: ").append(toIndentedString(reusePermission)).append("\n");
    sb.append("    siteId: ").append(toIndentedString(siteId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    viewPermission: ").append(toIndentedString(viewPermission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

