/*
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: 1.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * SummaryDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-25T11:31:19.558Z")
public class SummaryDTO {
  @SerializedName("average")
  private Map<String, Double> average = new HashMap<String, Double>();

  @SerializedName("code")
  private Integer code = null;

  @SerializedName("day")
  private Dequedouble day = null;

  @SerializedName("dayCost")
  private Dequedouble dayCost = null;

  @SerializedName("keyName")
  private String keyName = null;

  @SerializedName("latest")
  private Double latest = null;

  @SerializedName("latestString")
  private String latestString = null;

  @SerializedName("max")
  private Map<String, Integer> max = new HashMap<String, Integer>();

  @SerializedName("min")
  private Map<String, Integer> min = new HashMap<String, Integer>();

  @SerializedName("minutes5")
  private Dequedouble minutes5 = null;

  @SerializedName("minutes5cost")
  private Dequedouble minutes5cost = null;

  @SerializedName("minutes60")
  private Dequedouble minutes60 = null;

  @SerializedName("minutes60cost")
  private Dequedouble minutes60cost = null;

  @SerializedName("month")
  private Dequedouble month = null;

  @SerializedName("monthCost")
  private Dequedouble monthCost = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("url")
  private String url = null;

  public SummaryDTO average(Map<String, Double> average) {
    this.average = average;
    return this;
  }

  public SummaryDTO putAverageItem(String key, Double averageItem) {
    this.average.put(key, averageItem);
    return this;
  }

   /**
   * Get average
   * @return average
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, Double> getAverage() {
    return average;
  }

  public void setAverage(Map<String, Double> average) {
    this.average = average;
  }

  public SummaryDTO code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public SummaryDTO day(Dequedouble day) {
    this.day = day;
    return this;
  }

   /**
   * Get day
   * @return day
  **/
  @ApiModelProperty(example = "null", value = "")
  public Dequedouble getDay() {
    return day;
  }

  public void setDay(Dequedouble day) {
    this.day = day;
  }

  public SummaryDTO dayCost(Dequedouble dayCost) {
    this.dayCost = dayCost;
    return this;
  }

   /**
   * Get dayCost
   * @return dayCost
  **/
  @ApiModelProperty(example = "null", value = "")
  public Dequedouble getDayCost() {
    return dayCost;
  }

  public void setDayCost(Dequedouble dayCost) {
    this.dayCost = dayCost;
  }

  public SummaryDTO keyName(String keyName) {
    this.keyName = keyName;
    return this;
  }

   /**
   * Get keyName
   * @return keyName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getKeyName() {
    return keyName;
  }

  public void setKeyName(String keyName) {
    this.keyName = keyName;
  }

  public SummaryDTO latest(Double latest) {
    this.latest = latest;
    return this;
  }

   /**
   * Get latest
   * @return latest
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getLatest() {
    return latest;
  }

  public void setLatest(Double latest) {
    this.latest = latest;
  }

  public SummaryDTO latestString(String latestString) {
    this.latestString = latestString;
    return this;
  }

   /**
   * Get latestString
   * @return latestString
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLatestString() {
    return latestString;
  }

  public void setLatestString(String latestString) {
    this.latestString = latestString;
  }

  public SummaryDTO max(Map<String, Integer> max) {
    this.max = max;
    return this;
  }

  public SummaryDTO putMaxItem(String key, Integer maxItem) {
    this.max.put(key, maxItem);
    return this;
  }

   /**
   * Get max
   * @return max
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, Integer> getMax() {
    return max;
  }

  public void setMax(Map<String, Integer> max) {
    this.max = max;
  }

  public SummaryDTO min(Map<String, Integer> min) {
    this.min = min;
    return this;
  }

  public SummaryDTO putMinItem(String key, Integer minItem) {
    this.min.put(key, minItem);
    return this;
  }

   /**
   * Get min
   * @return min
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, Integer> getMin() {
    return min;
  }

  public void setMin(Map<String, Integer> min) {
    this.min = min;
  }

  public SummaryDTO minutes5(Dequedouble minutes5) {
    this.minutes5 = minutes5;
    return this;
  }

   /**
   * Get minutes5
   * @return minutes5
  **/
  @ApiModelProperty(example = "null", value = "")
  public Dequedouble getMinutes5() {
    return minutes5;
  }

  public void setMinutes5(Dequedouble minutes5) {
    this.minutes5 = minutes5;
  }

  public SummaryDTO minutes5cost(Dequedouble minutes5cost) {
    this.minutes5cost = minutes5cost;
    return this;
  }

   /**
   * Get minutes5cost
   * @return minutes5cost
  **/
  @ApiModelProperty(example = "null", value = "")
  public Dequedouble getMinutes5cost() {
    return minutes5cost;
  }

  public void setMinutes5cost(Dequedouble minutes5cost) {
    this.minutes5cost = minutes5cost;
  }

  public SummaryDTO minutes60(Dequedouble minutes60) {
    this.minutes60 = minutes60;
    return this;
  }

   /**
   * Get minutes60
   * @return minutes60
  **/
  @ApiModelProperty(example = "null", value = "")
  public Dequedouble getMinutes60() {
    return minutes60;
  }

  public void setMinutes60(Dequedouble minutes60) {
    this.minutes60 = minutes60;
  }

  public SummaryDTO minutes60cost(Dequedouble minutes60cost) {
    this.minutes60cost = minutes60cost;
    return this;
  }

   /**
   * Get minutes60cost
   * @return minutes60cost
  **/
  @ApiModelProperty(example = "null", value = "")
  public Dequedouble getMinutes60cost() {
    return minutes60cost;
  }

  public void setMinutes60cost(Dequedouble minutes60cost) {
    this.minutes60cost = minutes60cost;
  }

  public SummaryDTO month(Dequedouble month) {
    this.month = month;
    return this;
  }

   /**
   * Get month
   * @return month
  **/
  @ApiModelProperty(example = "null", value = "")
  public Dequedouble getMonth() {
    return month;
  }

  public void setMonth(Dequedouble month) {
    this.month = month;
  }

  public SummaryDTO monthCost(Dequedouble monthCost) {
    this.monthCost = monthCost;
    return this;
  }

   /**
   * Get monthCost
   * @return monthCost
  **/
  @ApiModelProperty(example = "null", value = "")
  public Dequedouble getMonthCost() {
    return monthCost;
  }

  public void setMonthCost(Dequedouble monthCost) {
    this.monthCost = monthCost;
  }

  public SummaryDTO status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public SummaryDTO url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SummaryDTO summaryDTO = (SummaryDTO) o;
    return Objects.equals(this.average, summaryDTO.average) &&
        Objects.equals(this.code, summaryDTO.code) &&
        Objects.equals(this.day, summaryDTO.day) &&
        Objects.equals(this.dayCost, summaryDTO.dayCost) &&
        Objects.equals(this.keyName, summaryDTO.keyName) &&
        Objects.equals(this.latest, summaryDTO.latest) &&
        Objects.equals(this.latestString, summaryDTO.latestString) &&
        Objects.equals(this.max, summaryDTO.max) &&
        Objects.equals(this.min, summaryDTO.min) &&
        Objects.equals(this.minutes5, summaryDTO.minutes5) &&
        Objects.equals(this.minutes5cost, summaryDTO.minutes5cost) &&
        Objects.equals(this.minutes60, summaryDTO.minutes60) &&
        Objects.equals(this.minutes60cost, summaryDTO.minutes60cost) &&
        Objects.equals(this.month, summaryDTO.month) &&
        Objects.equals(this.monthCost, summaryDTO.monthCost) &&
        Objects.equals(this.status, summaryDTO.status) &&
        Objects.equals(this.url, summaryDTO.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(average, code, day, dayCost, keyName, latest, latestString, max, min, minutes5, minutes5cost, minutes60, minutes60cost, month, monthCost, status, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SummaryDTO {\n");
    
    sb.append("    average: ").append(toIndentedString(average)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    dayCost: ").append(toIndentedString(dayCost)).append("\n");
    sb.append("    keyName: ").append(toIndentedString(keyName)).append("\n");
    sb.append("    latest: ").append(toIndentedString(latest)).append("\n");
    sb.append("    latestString: ").append(toIndentedString(latestString)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("    min: ").append(toIndentedString(min)).append("\n");
    sb.append("    minutes5: ").append(toIndentedString(minutes5)).append("\n");
    sb.append("    minutes5cost: ").append(toIndentedString(minutes5cost)).append("\n");
    sb.append("    minutes60: ").append(toIndentedString(minutes60)).append("\n");
    sb.append("    minutes60cost: ").append(toIndentedString(minutes60cost)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    monthCost: ").append(toIndentedString(monthCost)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

