/*
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: 1.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.GatewayDTO;
import org.junit.Test;

/**
 * API tests for GatewayapicontrollerApi
 */
public class GatewayapicontrollerApiTest {

    private final GatewayapicontrollerApi api = new GatewayapicontrollerApi();

    
    /**
     * addGateway
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addGatewayUsingPOSTTest() throws ApiException {
        GatewayDTO gatewayDTO = null;
        // GatewayDTO response = api.addGatewayUsingPOST(gatewayDTO);

        // TODO: test validations
    }
    
    /**
     * listGateways
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listGatewaysUsingGETTest() throws ApiException {
        String name = null;
        // GatewayListDTO response = api.listGatewaysUsingGET(name);

        // TODO: test validations
    }
    
}
