/*
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: 1.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.IntelligenceDTO;
import org.junit.Test;

/**
 * API tests for IntelligenceapicontrollerApi
 */
public class IntelligenceapicontrollerApiTest {

    private final IntelligenceapicontrollerApi api = new IntelligenceapicontrollerApi();

    
    /**
     * add
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addUsingPOSTTest() throws ApiException {
        IntelligenceDTO intelligenceDTO = new IntelligenceDTO();
        IntelligenceDTO response = api.addUsingPOST(intelligenceDTO);

        // TODO: test validations
    }
    
    /**
     * delete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUsingDELETETest() throws ApiException {
        Long intelligenceId = null;
        // IntelligenceDTO response = api.deleteUsingDELETE(intelligenceId);

        // TODO: test validations
    }
    
    /**
     * get
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsingGETTest() throws ApiException {
        Long intelligenceId = null;
        // IntelligenceDTO response = api.getUsingGET(intelligenceId);

        // TODO: test validations
    }
    
    /**
     * list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUsingGETTest() throws ApiException {
        // IntelligenceListDTO response = api.listUsingGET();

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUsingPOSTTest() throws ApiException {
        Long intelligenceId = null;
        IntelligenceDTO intelligenceDTO = null;
        // IntelligenceDTO response = api.updateUsingPOST(intelligenceId, intelligenceDTO);

        // TODO: test validations
    }
    
}
